compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-Please specify your access token}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"
